## NumPy - II

### Agenda:

### Array Reshaping & Resizing in NumPy

#### 1. reshape()
Change shape without changing data.

##### Notes:
- The total number of elements must remain the same
- reshape() returns a new view if possible (no copy)
- You can use -1 to let NumPy infer one dimension

#### 2. ravel()
- Flatten into 1-D (returns a view)
- Fast and memory efficient
- Changes reflect in the original array (if no copy made)

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, 4]])

In [3]:
a.shape

(2, 2)

In [4]:
print(a)

[[1 2]
 [3 4]]


In [5]:
print(a.ravel())

[1 2 3 4]


In [6]:
print(a)

[[1 2]
 [3 4]]


In [7]:
a_ravel = a.ravel()
print(a_ravel)
print(id(a))
print(id(a.ravel()))
print(id(a_ravel))

[1 2 3 4]
4376034160
4447555568
4447556048


In [8]:
# .__array_interface__['data'][0]

# This attribute gives you the actual memory address where the raw data begins

In [9]:
print(f'Data address of \'a\' : {a.__array_interface__['data'][0]}')

Data address of 'a' : 38997164960


In [10]:
print(f'Data address of a.ravel directly : {a.ravel().__array_interface__['data'][0]}')

Data address of a.ravel directly : 38997164960


In [11]:
print(f'Data address of a_ravel : {a_ravel.__array_interface__['data'][0]}')

Data address of a_ravel : 38997164960


In [12]:
a[0][0] = 11

In [13]:
a

array([[11,  2],
       [ 3,  4]])

In [14]:
print(f'Data address of \'a\' : {a.__array_interface__['data'][0]}')

Data address of 'a' : 38997164960


In [15]:
print(a_ravel)

[11  2  3  4]


In [16]:
a_ravel.shape

(4,)

In [17]:
a_ravel.ndim

1

In [18]:
type(a_ravel)

numpy.ndarray

#### 3. flatten()
Flatten into 1-D (returns a copy)

In [19]:
print(a)

[[11  2]
 [ 3  4]]


In [20]:
b = a.flatten()

In [21]:
print(b)

[11  2  3  4]


In [22]:
print(f'Data address of \'a\' : {a.__array_interface__['data'][0]}')
print(f'Data address of \'b\' : {b.__array_interface__['data'][0]}')

Data address of 'a' : 38997164960
Data address of 'b' : 38997165216


#### 4. resize()

- Resize Array In-place
- Unlike reshape(), it can change total size
- Data may be truncated or padded with zeros

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [25]:
print(arr.reshape(3, 2))

[[1 2]
 [3 4]
 [5 6]]


In [26]:
print(arr.reshape(3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

In [27]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [28]:
arr.resize((3, 3), refcheck=False)      # In-place : means changing the data without reassignment

In [29]:
print(arr)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [30]:
arr_1 = np.array([[1, 2, 3], [4, 5, 10]])

In [31]:
np.resize(arr_1, (5, 5))

array([[ 1,  2,  3,  4,  5],
       [10,  1,  2,  3,  4],
       [ 5, 10,  1,  2,  3],
       [ 4,  5, 10,  1,  2],
       [ 3,  4,  5, 10,  1]])

#### 5. squeeze()

- Removes single dimensional axes
- Useful for removing extra dimensions from image or model output shapes like (1, 28, 28, 1)

In [32]:
a = np.array([[[1], [2], [3]]])
print(a.shape)

(1, 3, 1)


In [33]:
b = np.squeeze(a)

In [34]:
b.shape

(3,)

In [35]:
print(b)

[1 2 3]


In [36]:
print(a)

[[[1]
  [2]
  [3]]]


In [37]:
c = np.array([[[1], [2], [3]], [[1], [2], [3]]])
print(c.shape)

(2, 3, 1)


In [38]:
d = np.squeeze(c)

In [39]:
d.shape

(2, 3)

In [40]:
print(c)

[[[1]
  [2]
  [3]]

 [[1]
  [2]
  [3]]]


In [41]:
print(d)

[[1 2 3]
 [1 2 3]]


| Function | Purpose | In-place | Returns Copy/View |
| :--- | :--- | :--- | :--- |
| reshape() | Change shape (same size) | ❌ | View (if possible) |
| resize() | Resize array (can change size) | ✅ | None |
| ravel() | Flatten array 1-D | ❌ | View |
| flatten() | Flatten array 1-D | ❌ | Copy |
| squeeze() | Remove dimensions of size 1 | ❌ | New array |

### Indexing & Slicing in NumPy $\text{---}$ (Beginner to Advanced)

#### 1. Slicing
##### Syntax:
- array[start : stop : step]

In [42]:
arr = np.array([10, 20, 30, 40, 50])

In [43]:
print(arr)

[10 20 30 40 50]


In [44]:
print(arr[0])

10


In [45]:
print(arr[-1])

50


In [46]:
print(arr[4])

50


In [47]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start : stop(exclusive) : step]

print(arr[1 : 4])

[20 30 40]


In [48]:
print(arr[1 : -1])

[20 30 40]


In [49]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start : stop(exclusive) : step]

print(arr[0 : 3])

[10 20 30]


In [50]:
print(arr[ : 3])

[10 20 30]


In [51]:
# arr = np.array([10, 20, 30, 40, 50])
# array[start : stop(exclusive) : step]
# [10, 30, 50]

print(arr[ : : 2])

[10 30 50]


In [52]:
print(arr[0 : arr.size : 2])

[10 30 50]


In [53]:
print(arr[0 : len(arr) : 2])

[10 30 50]


In [54]:
print(arr[ : : -1])     # reversing

[50 40 30 20 10]


In [55]:
list_a = [1, 2, 3, 4, 5, 6, 7]
print(list_a)
print(list_a[ : : -1])

[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]


#### 2. Indexing in 2-D Arrays

In [56]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [57]:
print(mat[0][1])

2


In [58]:
print(mat[0, 1])

2


In [59]:
print(mat[:, 2])

[3 6 9]


In [60]:
# [[1 2 3]
# [4 5 6]
# [7 8 9]]

# [[2 3]
# [5 6]]

print(mat[ : -1, 1 : ])

[[2 3]
 [5 6]]


In [61]:
# [[9 8 7]
#  [6 5 4]
#  [3 2 1]]

print(mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [62]:
print(mat[::-1])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 3. Boolean Indexing

In [63]:
arr = np.array([5, 10, 15, 20, 25])

In [64]:
# I want to get all elements greater than 15

In [65]:
l = []

for i in arr:
    if (i > 15):
        l.append(i)

l = np.array(l)
print(l)

[20 25]


In [66]:
print(arr[arr > 15])

[20 25]


In [67]:
print(arr > 15)

[False False False  True  True]


#### 4. Fancy Indexing

In [68]:
arr = np.array([100, 200, 300, 400, 500])
indices = [0, 2, 4]
print(arr[indices])

[100 300 500]


In [69]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

In [70]:
print(mat[[0, 1], 
          [2, 2]])

[3 6]


In [71]:
print(mat[mat > 5])

[6 7 8 9]


#### 5. Modifying With Indexing

In [72]:
arr = np.array([1, 2, 3, 4])
print(arr)
arr[2] = 10
print(arr)

[1 2 3 4]
[ 1  2 10  4]


In [73]:
arr[arr > 2] = 100
print(arr)

[  1   2 100 100]


#### 6. Indexing With np.where()

In [74]:
arr = np.array([5, 10, 15, 20, 25, 30])

In [75]:
idx = np.where(arr > 20)

In [76]:
print(idx)

(array([4, 5]),)


In [77]:
print(arr[idx])

[25 30]
