## NumPy: Real-World Assignment (15-02-2026-UDS-2.0)

In [1]:
import numpy as np

### 1. A 1D array of numbers from 0 to 9

In [2]:
arr_1_d = np.arange(0, 10)
print(arr_1_d)

[0 1 2 3 4 5 6 7 8 9]


### 2. A 3x3 matrix of all 5s

In [3]:
matrix_3_x_3 = np.full((3, 3), 5)
print(matrix_3_x_3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### 3. A 4x4 identity matrix

In [4]:
identity_matrix_4_x_4 = np.eye(4, 4)
print(identity_matrix_4_x_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 4. 10 evenly spaced numbers between 1 and 100

In [5]:
linspace_1 = np.linspace(1, 100, 10)
print(linspace_1)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


### 5. A 2x2 array with random values between 0 and 1

In [6]:
random_matrix_2_x_2 = np.random.rand(2, 2)
print(random_matrix_2_x_2)

[[0.96971553 0.55916395]
 [0.01886244 0.80371153]]
