## NumPy - I

### Agenda:
-  Advantages of NumPy Over Python
-  Arrays in NumPy
-  Data Types in NumPy
-  NumPy Array Attributes
-  Array Reshaping & Resizing in NumPy

In [1]:
import time

In [2]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.time()
c = [x + y for x, y in zip(a, b)]
end_p = time.time()
total_p = end_p - start_p
print(f'Python: {total_p}')

Python: 0.04892706871032715


In [3]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print(f'Python: {total_p}')

Python: 0.057733749999897555


In [4]:
import numpy as np

In [5]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print(f'NumPy: {total_n}')

NumPy: 0.004989708999346476


In [6]:
print(f'NumPy is faster than Python by : {(total_p / total_n):.2f}')

NumPy is faster than Python by : 11.57


### Advantages of Numpy over Python

Python lists are:
- Flexible but slow for mathematical operations
- Not designed for matrix math
- Does not support vectorized operations
- Memory inefficient for large numerical data

Why use NumPy?
- Faster than pure Python for numerical computations
- Vectorized Operations (no explicit loops)
- Broadcasting (operate on arrays of different shapes)
- Memory efficient
- Comes with powerful linear algebra, random tools, etc.

Use of NumPy:
- Scientific python

### Creating Arrays In NumPy

#### 1. np.array()

In [7]:
arr_1 = np.array([1, 2, 3])

print(arr_1)
print(type(arr_1))
print(type(arr_1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [8]:
arr_1

array([1, 2, 3])

In [9]:
arr_2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr_2)

[[1 2 3]
 [4 5 6]]


In [10]:
arr_2[0]

array([1, 2, 3])

In [11]:
arr_2[0][2]

np.int64(3)

In [12]:
type(arr_2[0])

numpy.ndarray

In [13]:
arr_3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 1], [1, 3, 1], [1, 4, 1]]])

print(arr_3)
print(type(arr_3))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 1]
  [1 3 1]
  [1 4 1]]]
<class 'numpy.ndarray'>


### Data Types in NumPy

In [14]:
arr_4 = np.array([1, 2, 3, 'hello'])

print(arr_4)
print(type(arr_4))

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [15]:
print(type(arr_4[1]))

<class 'numpy.str_'>


In [16]:
arr_4

array(['1', '2', '3', 'hello'], dtype='<U21')

In [17]:
arr_5 = np.array([1, 2, 3], dtype=np.int8)

print(arr_5)
print(type(arr_5))
print(type(arr_5[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [18]:
arr_6 = np.array([1, 2, 3, 'hello'], dtype=np.float16)

ValueError: could not convert string to float: 'hello'

In [19]:
arr_7 = np.array([1, 2, 3, '10'], dtype=np.float16)

In [20]:
print(arr_7)

[ 1.  2.  3. 10.]


In [21]:
arr_7

array([ 1.,  2.,  3., 10.], dtype=float16)

**Note:** *Arrays can have elements of only one data type.*

#### 2. np.arange(start, stop, step)

In [22]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [23]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [24]:
print(np.arange(1, 11, 2))

[1 3 5 7 9]


In [25]:
a = np.array(np.arange(1, 11, 2))

In [26]:
a

array([1, 3, 5, 7, 9])

In [27]:
b = np.arange(1, 11, 2)

In [28]:
b

array([1, 3, 5, 7, 9])

#### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [29]:
np_linspace_1 = np.linspace(1, 100, 4)
print(np_linspace_1)
print(type(np_linspace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [30]:
np_linspace_2 = np.linspace(1, 10, 10)
print(np_linspace_2)
print(type(np_linspace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [31]:
np_linspace_3 = np.linspace(1, 10, 4)
print(np_linspace_3)
print(type(np_linspace_3))

[ 1.  4.  7. 10.]
<class 'numpy.ndarray'>


In [32]:
np_linspace_4 = np.linspace(1, 10, 100)
print(np_linspace_4)
print(type(np_linspace_4))

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [33]:
for num in np.linspace(1, 10, 10):
    print(type(num))
    print(num)
    print(type(int(num)))
    print('=======================')

<class 'numpy.float64'>
1.0
<class 'int'>
<class 'numpy.float64'>
2.0
<class 'int'>
<class 'numpy.float64'>
3.0
<class 'int'>
<class 'numpy.float64'>
4.0
<class 'int'>
<class 'numpy.float64'>
5.0
<class 'int'>
<class 'numpy.float64'>
6.0
<class 'int'>
<class 'numpy.float64'>
7.0
<class 'int'>
<class 'numpy.float64'>
8.0
<class 'int'>
<class 'numpy.float64'>
9.0
<class 'int'>
<class 'numpy.float64'>
10.0
<class 'int'>


In [34]:
for num in np.linspace(1, 10, 10, dtype=np.int8):
    print(num)

1
2
3
4
5
6
7
8
9
10


#### 4. np.zeros(shape)
shape $\rightarrow$ shape of matrix

In [35]:
npz_1 = np.zeros(5)
print(npz_1)

[0. 0. 0. 0. 0.]


In [36]:
npz_2 = np.zeros(5, dtype=np.int8)
print(npz_2)

[0 0 0 0 0]


In [37]:
npz_3 = np.zeros((5, 5))
print(npz_3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [38]:
npz_4 = np.zeros((5, 5), dtype=np.int8)
print(npz_4)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [39]:
npz_5 = np.zeros((5, 5, 5))
print(npz_5)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [40]:
npz_5.ndim      # tells the dimension of the array or matrix

3

In [41]:
npz_6 = np.zeros((2, 5, 5))
print(npz_6)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 5. np.ones(shape)
shape $\rightarrow$ shape of matrix

In [42]:
npo_1 = np.ones((2, 3))
print(npo_1)

[[1. 1. 1.]
 [1. 1. 1.]]


#### 6. np.full(shape, fill_value)
- shape $\rightarrow$ shape of matrix
- fill_value $\rightarrow$ what value to fill

In [43]:
npf_1 = np.full((2, 3), 10)
print(npf_1)

[[10 10 10]
 [10 10 10]]


In [44]:
npf_2 = np.full((2, 3), 10.0)
print(npf_2)

[[10. 10. 10.]
 [10. 10. 10.]]


In [45]:
npf_3 = np.full((2, 3), 10, dtype=np.float16)
print(npf_3)

[[10. 10. 10.]
 [10. 10. 10.]]


#### 7. np.eye(shape)
- shape $\rightarrow$ shape of matrix
- does not exist in 1-D
- minimum of 2-D shape

In [46]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
print(np.eye(2, 3))

[[1. 0. 0.]
 [0. 1. 0.]]


In [48]:
print(np.eye(3, 2))

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [49]:
print(np.eye(7, 7))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [50]:
print(np.eye(7, 7, 0))

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [51]:
print(np.eye(7, 7, -1))

[[0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]]


In [52]:
print(np.eye(7, 7, 1))

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [53]:
print(np.eye(7, 7, -3))

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


In [54]:
print(np.eye(7, 7, 3))

[[0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 8. np.empty(shape)
shape -> shape of matrix

In [55]:
np.empty((2, 2), dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [56]:
np.empty((2, 2), dtype=np.float16)

array([[0., 0.],
       [0., 0.]], dtype=float16)

In [57]:
start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)

9.429100009583635e-05


In [58]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

7.224999990285141e-05


In [59]:
print(np.empty((3, 7, 7), dtype=np.int8))

[[[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]

 [[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]]


#### 9. np.random.rand(shape)

- It will give values between 0 and 1
- ML weights random initialization

In [60]:
np.random.rand(8)

array([0.85195004, 0.97697599, 0.62285772, 0.44605509, 0.71105343,
       0.5784277 , 0.12440695, 0.87550156])

In [61]:
np.random.rand(1, 8)

array([[0.53100823, 0.14670666, 0.02283374, 0.5411363 , 0.31537399,
        0.08079289, 0.69997638, 0.77829628]])

In [62]:
np.random.rand(2, 8)

array([[0.25728632, 0.13718762, 0.36464468, 0.99038601, 0.46667264,
        0.27896796, 0.35736817, 0.8778589 ],
       [0.7041624 , 0.10067287, 0.48528607, 0.09561885, 0.41652464,
        0.53545884, 0.50260234, 0.98766125]])

**Note:** *1-D array is called as vector.*

### NumPy Array Attributes

#### 1. ndarray.shape

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


#### 2. ndarray.ndim

In [64]:
print(arr.ndim)

2


#### 3. ndarray.size
Returns the total number of elements in the array.

In [65]:
print(arr.size)

6


#### 4. ndarray.dtype
Tells the data type of the array elements.

In [66]:
print(arr.dtype)

int64


#### 5. ndarray.itemsize
Returns the size in bytes for one element.

- 1 byte $\rightarrow$ 8 bits
- int8 $\rightarrow$ 1 * 8 bits
- int16 $\rightarrow$ 2 * 8 bits
- int32 $\rightarrow$ 4 * 8 bits
- int64 $\rightarrow$ 8 * 8 bits

In [67]:
print(arr.itemsize)

8


#### 6. ndarray.nbytes
Total number of bytes consumed by the array.

In [68]:
print(arr.nbytes)

48


#### 7. ndarray.T
Returns the transpose of the matrix.

In [69]:
print(arr)      # 2 rows, 3 colums

[[1 2 3]
 [4 5 6]]


In [70]:
print(arr.T)      # 3 rows, 2 colums

[[1 4]
 [2 5]
 [3 6]]


In [71]:
print(arr.T.shape)

(3, 2)


### Array Reshaping & Resizing in NumPy

#### 1. reshape()
Change shape without changing data.

##### Notes:
- The total number of elements must remain the same
- reshape() returns a new view if possible (no copy)
- You can use -1 to let NumPy infer one dimension

In [72]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [73]:
# 2x3
# 3x2
# 6x1

In [74]:
reshaped_1 = arr.reshape(2, 3)
print(reshaped_1)

[[1 2 3]
 [4 5 6]]


In [75]:
reshaped_2 = arr.reshape(3, 2)
print(reshaped_2)

[[1 2]
 [3 4]
 [5 6]]


In [76]:
reshaped_3 = arr.reshape(1, 6)
print(reshaped_3)
print(reshaped_3.shape)
print(reshaped_3.ndim)

[[1 2 3 4 5 6]]
(1, 6)
2


In [77]:
reshaped_4 = arr.reshape(6, 1)
print(reshaped_4)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [78]:
array = np.array([1, 2, 3, 4, 5, 6, 56, 100, 789])
print(array)
print(array.shape)

[  1   2   3   4   5   6  56 100 789]
(9,)


In [79]:
reshaped_5 = array.reshape(3, -1)
print(reshaped_5)
print(reshaped_5.shape)

[[  1   2   3]
 [  4   5   6]
 [ 56 100 789]]
(3, 3)


In [80]:
reshaped_6 = array.reshape(-1, 3)
print(reshaped_6)
print(reshaped_6.shape)

[[  1   2   3]
 [  4   5   6]
 [ 56 100 789]]
(3, 3)


In [81]:
reshaped_7 = array.reshape(2, -1)
print(reshaped_7)
print(reshaped_7.shape)

ValueError: cannot reshape array of size 9 into shape (2,newaxis)

In [82]:
reshaped_7 = array.reshape(-1, -1)
print(reshaped_7)
print(reshaped_7.shape)

ValueError: can only specify one unknown dimension